### ISSUE TITLE
victi.ms site is down

### ISSUE THREAD

**Issue by bikscp** [victims/victims-web#137]
Hi Team,

I found the site victi.ms is down for recent days.
Could you give some information aobut when it is coming back online, please?

Thanks
Bk

**Comment by abn** [comment]
@bikscp our current hosting service seems to be, broken. We will look at bringing this back online this week as time permits.

**Comment by ashcrow** [comment]
@bikscp it should be back up and running now.

FYI @abn I'm likely going to look at splitting the web ui and the services up into different code bases in the near future.

**Comment by jaminJay** [comment]
@ashcrow, unfortunately the service seems down again this morning (AEST).

**Comment by ashcrow** [comment]
Should be back.

**Comment by jaminJay** [comment]
Must be a routing issue?  Cannot access from two different networks and http://downforeveryoneorjustme.com/victi.ms returns down.

**Comment by ashcrow** [comment]
@jaminJay interesting.Looks like without the www we are no longer forwarding to https. I'm looking into it as it shouldn't just hang, it should forward.

**Comment by ashcrow** [comment]
@jaminJay the bare domain was pointed to the old VIP while www was pointing to the newer one. The older VIP was retired today so it victi.ms stopped responding while www.victi.ms continued working as expected. I've updated DNS so both point at the new VIP but it will take a bit to make it out.

**Comment by ashcrow** [comment]
Tested [http,https]//{victi.ms,www.victi.ms} with 8.8.8.8 and they resolves properly now.

**Comment by jaminJay** [comment]
@ashcrow, thanks for your quick turnaround (confirmed as working).
