### ISSUE TITLE
Host CVRF data about vulnerabilites

### ISSUE THREAD

**Issue by jasinner** [victims/victims-web#147]
We should host [CVRF](http://www.icasi.org/the-common-vulnerability-reporting-framework-cvrf-v1-1/) data about the vulnerablities in the database so that it can be consumed by organizations such as NIST in their [NVD](https://nvd.nist.gov).

This would require mapping Maven GAVs to [CPE names](https://nvd.nist.gov/cpe.cfm), and requesting new CPE names where they don't already exist.

Here is [an example of CVRF data](https://www.redhat.com/security/data/cvrf/) hosted by Red Hat for enterprise products.

**Comment by ashcrow** [comment]
Sounds like a good idea to me. Do you have any ideas on how you'd expect the data to be available within the API?

**Comment by jasinner** [comment]
Looking at the [Red Hat Enterprise data](https://www.redhat.com/security/data/cvrf/) it can be a list of static files.  It might actually be best done as part of separate project from victims-web?

**Comment by ashcrow** [comment]
@jasinner as in outside of the API as well -- or just outside of the web ui?

Slightly related: I'm keen on trying to get back to working on the API side of things if we (as in anyone who has opinions on the design of the API) is happy with with design. I'd like to replace the aging all-in-one ``victims-web`` for backend stuff.

**Comment by jasinner** [comment]
We have to decide what to use as the 'vendor' in any CPE we issue. One idea proposed [here](https://www.evernote.com/shard/s3/sh/e2cb76bb-4e07-4b42-aa2b-999d9681ff50/5d81c1a7bc25a9a2) is to use 'apache-maven-central' as the vendor. 
This seems like a good idea for dependencies from Maven Central. However since we are [incorporating data from other Maven repositories](https://github.com/victims/victims-cve-db/issues/9), we should allow the vendor field to reflect other repositories.

**Comment by ashcrow** [comment]
If we use ``apache-maven-central`` as the vendor we could use ``$NAME-maven-$OPTIONAL`` as a pattern for other maven CPE vendors. Does that seem reasonable?

**Comment by jasinner** [comment]
I like the idea of using $NAME-maven-$OPTIONAL. However I'm going to close this task, and create a new project that's not part of victims-web to start working on this issue. https://github.com/jasinner/victims-cvrf
